from __future__ import annotations


CONFIG_INVALID = "CONFIG_INVALID"
MONGO_CONFIG_INVALID = "MONGO_CONFIG_INVALID"
MONGO_UNAVAILABLE = "MONGO_UNAVAILABLE"
MONGO_SCHEMA_INVALID = "MONGO_SCHEMA_INVALID"
MONGO_WRITE_FAILED = "MONGO_WRITE_FAILED"
OPENVIKING_CONFIG_INVALID = "OPENVIKING_CONFIG_INVALID"
OPENVIKING_AUTH_FAILED = "OPENVIKING_AUTH_FAILED"
PROVIDER_KEY_MISSING = "PROVIDER_KEY_MISSING"
PROVIDER_NOT_APPROVED = "PROVIDER_NOT_APPROVED"
PROVIDER_NOT_ENABLED = "PROVIDER_NOT_ENABLED"
PROVIDER_HTTP_CLIENT_ERROR = "PROVIDER_HTTP_CLIENT_ERROR"
PROVIDER_HTTP_SERVER_ERROR = "PROVIDER_HTTP_SERVER_ERROR"
TOOL_PARAMS_INVALID = "TOOL_PARAMS_INVALID"
TOOL_RUNTIME_CONTEXT_MISSING = "TOOL_RUNTIME_CONTEXT_MISSING"
TOOL_WORKER_MISMATCH = "TOOL_WORKER_MISMATCH"
TOOL_CONTEXT_INCOMPLETE = "TOOL_CONTEXT_INCOMPLETE"
TOOL_SUBPROCESS_TIMEOUT = "TOOL_SUBPROCESS_TIMEOUT"
TOOL_PROTOCOL_ERROR = "TOOL_PROTOCOL_ERROR"
MARKET_INVALID = "MARKET_INVALID"
TICKER_INVALID = "TICKER_INVALID"
DATE_INVALID = "DATE_INVALID"
L2_TARGET_INVALID = "L2_TARGET_INVALID"
L2_WRITE_FAILED = "L2_WRITE_FAILED"
L2_READBACK_FAILED = "L2_READBACK_FAILED"
L2_HASH_MISMATCH = "L2_HASH_MISMATCH"
URL_QUERY_INVALID = "URL_QUERY_INVALID"
PACK_SCHEMA_INVALID = "PACK_SCHEMA_INVALID"
PACK_FIELD_SOURCE_INVALID = "PACK_FIELD_SOURCE_INVALID"
BRIEF_UNSUPPORTED_CONCLUSION = "BRIEF_UNSUPPORTED_CONCLUSION"
BRIEF_SECRET_LEAK = "BRIEF_SECRET_LEAK"
BRIEF_MACHINE_NOISE = "BRIEF_MACHINE_NOISE"
TECHLAB_INPUT_INVALID = "TECHLAB_INPUT_INVALID"
TECHLAB_INDICATOR_FAILED = "TECHLAB_INDICATOR_FAILED"
TECHLAB_CHART_FAILED = "TECHLAB_CHART_FAILED"


class FrontlineConfigError(ValueError):
    def __init__(self, code: str, message: str) -> None:
        self.code = code
        self.message = message
        super().__init__(f"{code}: {message}")


class FrontlineValidationError(ValueError):
    def __init__(self, code: str, message: str) -> None:
        self.code = code
        self.message = message
        super().__init__(f"{code}: {message}")
