from __future__ import annotations

from .models import endpoint, no_batch

TUSHARE_DOC = "https://tushare.pro/document/2"
AUTH = "tushare_body_token"
BUCKET = "ratelimit:tushare"


ENDPOINTS = (
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.daily",
        official_path_or_api_name="daily",
        method="POST",
        required_params=("ts_code",),
        optional_params=("start_date", "end_date", "trade_date", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        batch_policy=no_batch(),
        official_doc_ref=TUSHARE_DOC,
        request_template={"api_name": "daily", "params": {"ts_code": "<symbol>"}},
        response_shape={"items": "daily A-share OHLCV rows"},
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.daily_basic",
        official_path_or_api_name="daily_basic",
        method="POST",
        required_params=("ts_code",),
        optional_params=("start_date", "end_date", "trade_date", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
        request_template={"api_name": "daily_basic", "params": {"ts_code": "<symbol>"}},
        response_shape={"items": "valuation and market-cap rows"},
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.moneyflow",
        official_path_or_api_name="moneyflow",
        method="POST",
        required_params=("ts_code",),
        optional_params=("start_date", "end_date", "trade_date", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
        request_template={"api_name": "moneyflow", "params": {"ts_code": "<symbol>"}},
        response_shape={"items": "stock capital-flow rows"},
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.moneyflow_ths",
        official_path_or_api_name="moneyflow_ths",
        method="POST",
        required_params=("ts_code",),
        optional_params=("start_date", "end_date", "trade_date", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.moneyflow_ind_dc",
        official_path_or_api_name="moneyflow_ind_dc",
        method="POST",
        required_params=(),
        optional_params=("trade_date", "content_type", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.moneyflow_ind_ths",
        official_path_or_api_name="moneyflow_ind_ths",
        method="POST",
        required_params=(),
        optional_params=("trade_date", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.moneyflow_cnt_ths",
        official_path_or_api_name="moneyflow_cnt_ths",
        method="POST",
        required_params=(),
        optional_params=("trade_date", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.fina_indicator",
        official_path_or_api_name="fina_indicator",
        method="POST",
        required_params=("ts_code",),
        optional_params=("start_date", "end_date", "period", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
        response_shape={"items": "financial indicator rows"},
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.income",
        official_path_or_api_name="income",
        method="POST",
        required_params=("ts_code",),
        optional_params=("start_date", "end_date", "period", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.balancesheet",
        official_path_or_api_name="balancesheet",
        method="POST",
        required_params=("ts_code",),
        optional_params=("start_date", "end_date", "period", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.cashflow",
        official_path_or_api_name="cashflow",
        method="POST",
        required_params=("ts_code",),
        optional_params=("start_date", "end_date", "period", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.anns_d",
        official_path_or_api_name="anns_d",
        method="POST",
        required_params=("ts_code",),
        optional_params=("start_date", "end_date", "ann_date", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
        response_shape={"items": "announcement metadata rows"},
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.irm_qa_sh",
        official_path_or_api_name="irm_qa_sh",
        method="POST",
        required_params=("ts_code",),
        optional_params=("trade_date", "start_date", "end_date", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.irm_qa_sz",
        official_path_or_api_name="irm_qa_sz",
        method="POST",
        required_params=("ts_code",),
        optional_params=("trade_date", "start_date", "end_date", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.hk_daily",
        official_path_or_api_name="hk_daily",
        method="POST",
        required_params=("ts_code",),
        optional_params=("start_date", "end_date", "trade_date", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.hk_daily_adj",
        official_path_or_api_name="hk_daily_adj",
        method="POST",
        required_params=("ts_code",),
        optional_params=("start_date", "end_date", "trade_date", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
    ),
    endpoint(
        provider_id="official_api_tushare",
        source_type="tushare",
        endpoint_id="tushare.hk_fina_indicator",
        official_path_or_api_name="hk_fina_indicator",
        method="POST",
        required_params=("ts_code",),
        optional_params=("start_date", "end_date", "period", "fields"),
        auth=AUTH,
        rate_limit_bucket=BUCKET,
        official_doc_ref=TUSHARE_DOC,
    ),
)

